---
- name: restart kea-dhcp4-server
  service:
    name: kea-dhcp4-server
    state: restarted
    enabled: yes

- name: restart kea-dhcp6-server
  service:
    name: kea-dhcp6-server
    state: restarted
    enabled: yes

- name: restart radvd
  service:
    name: radvd
    state: restarted
    enabled: yes
